name: Publish to PSGallery

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/Az.RuntimeEnvironment/*.ps1'

permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build PS Module
        shell: pwsh
        run: |
          ./src/Build.Module.ps1

      - name: Publish to PSGallery
        uses: aammirmirza/Publish2PSGallery@PSGallery_v2
        with:
          NuGetApiKey: ${{ secrets.NuGetApiKey }}
          modulePath: ./src/Az.RuntimeEnvironment
